server:
  port: 8090

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.17.0.2:3306/toy_twitter?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

